swagger: "2.0"
info:
  version: "0.0.1"
  title: ShellAPI
host: localhost:10010
basePath: /apiV1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:

  /swagger:
    x-swagger-pipe: swagger_raw
    
  /command/echo:
    x-swagger-router-controller: commands
    post:
      description: Run an echo command, and receive its output
      operationId: echoCommand
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              message:
                type: string
            required:
              - message
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/CommandOutputResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

definitions:
  CommandOutputResponse:
    required:
      - output
    properties:
      output:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
