swagger: "2.0"
info:
  version: "0.0.1"
  title: ShellAPI
host: localhost:10010
basePath: /apiV1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:

  /swagger:
    x-swagger-pipe: swagger_raw
    
  /command/echo:
    x-swagger-router-controller: commands
    post:
      description: Run an echo command, and receive its output
      operationId: echoCommand
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              message:
                type: string
            required:
              - message
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/CommandOutputResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
            
  /command/grep:
    x-swagger-router-controller: commands
    post:
      description: text search files using grep like options, receive matching acurences 
      operationId: grepCommand
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/GrepCommand"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/CommandOutputResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

definitions:
  GrepCommand:
    required:
      - searchPhrase
    properties:
      searchPhrase:
        description: the prase to search for in the file or files
        type: string
        minLength: 1
        maxLength: 100
      filesToSearch:
        description: the files to search in, if left undefined then all avalible files will be used in the grep
        type: array
        minLength: 1
        maxLength: 10
        items:
          description: the file name to search in
          type: string
          minLength: 1
          maxLength: 30
        
  CommandOutputResponse:
    required:
      - output
    properties:
      output:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
